// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Parse the number of times to call Math.random
		int N = Integer.parseInt(args[0]);

		int numberOfCalls = 0;
		int smallerThanHalf = 0;
		int biggerThanHalf = 0;

		// run the test for the specified number of times
		while (numberOfCalls < N) {
			double randomNumber = Math.random();
			if (randomNumber <= 0.5 ) {
				smallerThanHalf++;
			}
			else {
				biggerThanHalf++;
			}
			numberOfCalls++;			
		}

		System.out.println("> 0.5 :" + biggerThanHalf + " times");
		System.out.println("<= 0.5 :" + smallerThanHalf + " times");
		
		// Calculate and print the ratio after checking for edge case of division by zero
		String ratioMassage = (biggerThanHalf == 0 ? "Ratio: Undefined (all values <= 0.5)" : "Ratio: " + ((double) smallerThanHalf / biggerThanHalf) );
		System.out.println(ratioMassage);
	}
}
